name: flutter_betclac
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  english_words: ^4.0.0
  flutter:
    sdk: flutter
  path: ^1.9.1
  provider: ^6.1.5+1
  sqflite_common_ffi: ^2.3.4+1
  sqlite3_flutter_libs: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true